version: '3.7'

volumes:
  prometheus: {}
  grafana: {}

services:

  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    volumes:
      - ./infra/prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - app
    volumes:
      - grafana:/var/lib/grafana
      - ./infra/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./infra/grafana/config.monitoring
    ports:
      - 3000:3000
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    restart: always
