global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'tele2'
    static_configs:
         - targets: ['app:8080']

